name: Reading from the Environment

on:
  workflow_dispatch:
  push:

jobs:
  example:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: qoomon/actions--context@v2
        id: context

      - run: |
          echo "Current Environment: ${{ steps.context.outputs.environment }}"
          echo "Job Logs: ${{ steps.context.outputs.job_log_url }}"
      
      - run: |
          echo "${{ vars.ENV_NAME }}"