name: Reading from the Environment

on:
  workflow_dispatch:
  push:

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]

    permissions:
      contents: read
      id-token: write # Required for AWS OIDC authentication

    runs-on: ${{ matrix.os }}

    environment: 
      name: development
      url: ${{ steps.main.outputs.url }}

    steps:
      - uses: actions/checkout@v4

      - name: Setting env var
        run: |
          echo "BOB=DOBBS" >> $GITHUB_ENV

      - name: What Can I See
        run: |
          /bin/env

      - name: See bob
        run: |
          echo "$BOB,${BOB}"

      - name: Print environment name
        run: |
          echo "Environment name: ${{ job.environment.name }}"