name: Reading from the Environment

on:
  workflow_dispatch:
  push:

jobs:
  example:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Dump vars context
        env:
          VARS_JSON: ${{ toJSON(vars) }}
        run: echo "${VARS_JSON}" > env.json
      - name: Dump env.json to env.bash file
        run: |
          cat env.json | jq \
            --compact-output \
            --raw-output \
            --monochrome-output \
            'to_entries | map("echo \"\(.key)=\(.value)\" >> $GITHUB_ENV") | .[]' > env.bash
      - name: Show env.bash
        run: bash ./env.bash
      - name: Show GITHUB_ENV
        run: echo "$SOME_VAR_1"
