name: Reading from the Environment

on:
  workflow_dispatch:
  push:

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]

    permissions:
      contents: read
      id-token: write # Required for AWS OIDC authentication

    runs-on: ${{ matrix.os }}

    environment: ${{ var.ENV_NAME }} 

    steps:
      name: In env ${{ var.ENV_NAME }}
      run: |
        echo "env_name: ${{ var.ENV_NAME }}"
