name: Reading from the Environment

on:
  workflow_dispatch:
  push:

jobs:
  example:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Dump vars context
        env:
          VARS_JSON: ${{ toJSON(vars) }}
        run: echo "${VARS_JSON}"
      - name: Can I just print VARS_JSON
        run: echo "${{vars}}"
